### ISSUE TITLE
Hit Boxes bugging out

### ISSUE THREAD

**Issue by Crazypersonalph** [y330/Pydash#1]
Hello y330,
I don't think this project is still maintained, but I though I might put this issue here.
When you run into a box, ***not a spike***, the game ends, even though I believe the game should go on.
I don't know if this will be patched or not, or if I need to implement my own patch, as I want to use this project for an AI project.
Thanks in advance.

**Comment by Crazypersonalph** [comment]
The hitboxes are kinda jank.

**Comment by Crazypersonalph** [comment]
lol, it was an intended consequence, looked at the code.

**Comment by tianhan4** [comment]
> lol, it was an intended consequence, looked at the code.

k
